from snakemake.utils import min_version

min_version("6.10.0")

# Configuration file containing all user-specified settings
configfile: "config/config.yml"

# # Debug information
# print("Configuration:")
# print(config)

report: "report/workflow.rst"

# include: "rules/qiime2_viz.smk"
# include: "rules/visual_types.smk"


rule FINAL_TARGET:
    input:
        "docs/index.html",

        # "data/feature.qza", 
        # "data/taxonomy.qza", 
        # "data/metadata.tsv",
        # "data/shannon.qza",

        # "resources/feature_table.qza",
        # "resources/sample_metadata.tsv",
        # "resources/taxonomy.qza",
        # "resources/rooted_tree.qza",
        # "resources/shannon_vector.qza",
        
        # "data/qiime2_phyloseq.rds",
        # "data/qiime2_phyloseq_demo.rds",

		# "figures/q2r_venndiagram.svg",
		# "figures/q2r_lineplot.svg",
		# "figures/q2r_jitterplot.svg",
		# "figures/q2r_pcoa.svg",
		# "figures/q2r_heatmap.svg",
		# "figures/q2r_barplot.svg",


        # expand("visual_types/heatmaps/{prefix}.Rmd", prefix=config["heatmaps"]),
        # expand("visual_types/hclusters/{prefix}.Rmd", prefix=config["hclusters"]),
        # expand("visual_types/barplots/{prefix}.Rmd", prefix=config["barplots"]),
        # expand("visual_types/boxplots/{prefix}.Rmd", prefix=config["boxplots"]),
        # expand("visual_types/ordinations/{prefix}.Rmd", prefix=config["ordinations"]),
        # expand("visual_types/phylotrees/{prefix}.Rmd", prefix=config["phylotrees"]),


# Rule to generate the rule graph and create the dags folder if it doesn't exist
rule generate_rulegraph:
    output:
        directory("dags"),
        "dags/rulegraph.png",
        "dags/rulegraph.svg",

    shell:
        """
        snakemake --unlock;
        mkdir -p {output[0]};
        snakemake --rulegraph | dot -Tpng > {output[1]};
        snakemake --rulegraph | dot -Tsvg > {output[2]};
        """

# Rule to generate a directory tree
rule project_tree:
    output:
        directory("output"),
        "reports/project_tree.txt"
    shell:
        """
        snakemake --unlock \
        && mkdir -p {output[0]} \
        && echo "Project Tree" > {output[1]} \
        && tree -L 2 . >> {output[1]}
        """

# Rule to generate SnakeMake report
rule snakemake_report:
    output:
        "reports/snakemake_report.html"
    shell:
        "snakemake --keep-going --use-conda --report {output[0]}"

rule import_processed_data:
    output:
        features="data/feature.qza", 
        taxonomy = "data/taxonomy.qza", 
        metadata="data/metadata.tsv",
        shannon="data/shannon.qza",
        rda="data/processed_data.rda"
    conda:
        "envs/environment.yml"
    script:
        "scripts/importdata.R"


rule import_demo_qiime2_data:
    output:
        "resources/feature_table.qza",
        "resources/sample_metadata.tsv",
        "resources/taxonomy.qza",
        "resources/rooted_tree.qza",
        "resources/shannon_vector.qza",
    conda:
        "envs/environment.yml"
    script:
        "scripts/importdata.R"



rule qiime2_phyloseq_object:
    input:
        q2data=rules.import_processed_data.output,
        demo=rules.import_demo_qiime2_data.output,
    output:
        "data/qiime2_phyloseq.rds",
        "data/qiime2_phyloseq_demo.rds",
    conda:
        "envs/environment.yml"
    script:
        "scripts/phyloseqobject.R"


# rule convert_qiime2csv:
#     input:
#         features="data/feature.qza", 
#         taxonomy = "data/taxonomy.qza", 
#         metadata="data/metadata.tsv",
#         shannon="data/shannon.qza",
#     output:
#         "data/features.csv",
#         "data/metadata.csv",
#         "data/taxonomy.csv",
#         "data/shannon.csv",
#     conda:
#         "envs/environment.yml"
#     script:
#         "scripts/qiime2csv.R"

rule venn_diagram:
    input:
        "data/metadata.csv",
        "data/shannon.csv",
    output:
        report("figures/q2r_venndiagram.svg", caption="report/venndiagram.rst", category="VennDiagram"),
    script:
        "scripts/venndiagram.R"


rule line_point_plot:
    input:
        demo=rules.import_demo_qiime2_data.output,

    output:
        report("figures/q2r_lineplot.svg", caption="report/lineplot.rst", category="LinePlot"),
    script:
        "scripts/lineplot.R"


rule jitter_plot:
    input:
        demo=rules.import_demo_qiime2_data.output,
    output:
        report("figures/q2r_jitterplot.svg", caption="report/jitterplot.rst", category="JitterPlot"),
    script:
        "scripts/jitterplot.R"



rule pcoa_ordination:
    input:
        demo=rules.import_demo_qiime2_data.output,
    output:
        report("figures/q2r_pcoa.svg", caption="report/pcoa.rst", category="PCoA"),
    script:
        "scripts/pcoa.R"



rule heatmap_plot:
    input:
        demo=rules.import_demo_qiime2_data.output,
    output:
        report("figures/q2r_heatmap.svg", caption="report/heatmap.rst", category="HeatMap"),
    script:
        "scripts/heatmap.R"


rule taxa_barplot:
    input:
        demo=rules.import_demo_qiime2_data.output,
    output:
        report("figures/q2r_barplot.svg", caption="report/barplot.rst", category="Taxa Barplot"),
    script:
        "scripts/barplot.R"

rule create_barplots:
    input:
        "data/mothur_composite.csv",
        "data/qiime2_composite.csv"
    output:
        "figures/taxon_barplot.png",
        "figures/taxon_barplot.svg"
    script:
        "scripts/create_barplots.R"


rule render_bs4_book:
    input:
        "index.Rmd",
        # "reports/snakemake_report.html",
        "reports/project_tree.txt",
        "dags/rulegraph.png",
        "dags/rulegraph.svg",
        "figures/taxon_barplot.png",
        "figures/taxon_barplot.svg"
    
    output:
        "docs/index.html"
    shell:
        "R -e 'bookdown::render_book(input = \"index.Rmd\", output_format = \"bookdown::bs4_book\", output_dir = \"docs\")'"
